### ISSUE TITLE
Error in running locally..

### ISSUE THREAD

**Issue by eledger** [girirajsharma/exmong#2]
I am new to nodejs and tried to run locally and get this at startup..
any ideas on how to fix this?

TypeError: Cannot read property 'ObjectID' of undefined
    at Object.<anonymous> (C:\nodejs\crud\exmong\app.js:33:32)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by girirajsharma** [comment]
@eledger Can you try it again. I have fixed and pushed some changes.

**Comment by eledger** [comment]
Thanks..worked like a charm..
